# Kernel SVM

## Importing the libraries

In [2]:
import numpy as np
import pandas as pd

## Importing the dataset

In [3]:
df = pd.read_csv('heart.csv')
df.head() 

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [5]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [6]:
X= df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [7]:
X

array([[63.,  1.,  3., ...,  0.,  0.,  1.],
       [37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       ...,
       [68.,  1.,  0., ...,  1.,  2.,  3.],
       [57.,  1.,  0., ...,  1.,  1.,  3.],
       [57.,  0.,  1., ...,  1.,  1.,  2.]])

In [8]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

## Splitting the dataset into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [10]:
X_test

array([[6.20e+01, 0.00e+00, 0.00e+00, 1.60e+02, 1.64e+02, 0.00e+00,
        0.00e+00, 1.45e+02, 0.00e+00, 6.20e+00, 0.00e+00, 3.00e+00,
        3.00e+00],
       [5.60e+01, 1.00e+00, 1.00e+00, 1.30e+02, 2.21e+02, 0.00e+00,
        0.00e+00, 1.63e+02, 0.00e+00, 0.00e+00, 2.00e+00, 0.00e+00,
        3.00e+00],
       [4.80e+01, 1.00e+00, 0.00e+00, 1.30e+02, 2.56e+02, 1.00e+00,
        0.00e+00, 1.50e+02, 1.00e+00, 0.00e+00, 2.00e+00, 2.00e+00,
        3.00e+00],
       [6.00e+01, 1.00e+00, 0.00e+00, 1.30e+02, 2.06e+02, 0.00e+00,
        0.00e+00, 1.32e+02, 1.00e+00, 2.40e+00, 1.00e+00, 2.00e+00,
        3.00e+00],
       [5.00e+01, 1.00e+00, 0.00e+00, 1.50e+02, 2.43e+02, 0.00e+00,
        0.00e+00, 1.28e+02, 0.00e+00, 2.60e+00, 1.00e+00, 0.00e+00,
        3.00e+00],
       [6.30e+01, 1.00e+00, 0.00e+00, 1.40e+02, 1.87e+02, 0.00e+00,
        0.00e+00, 1.44e+02, 1.00e+00, 4.00e+00, 2.00e+00, 2.00e+00,
        3.00e+00],
       [5.60e+01, 1.00e+00, 0.00e+00, 1.30e+02, 2.83e+02, 1.00e+00,
  

In [11]:
y_test

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1])

## Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
X_test

array([[ 0.82357149, -1.50674161, -0.95800789,  1.64732574, -1.60248069,
        -0.41803981, -1.02735505, -0.19244949, -0.68313005,  4.72344331,
        -2.30421185,  2.26339365,  1.16707438],
       [ 0.16688516,  0.6636838 ,  0.02021114, -0.07944077, -0.49359042,
        -0.41803981, -1.02735505,  0.5731304 , -0.68313005, -0.93352855,
         0.96628239, -0.72428597,  1.16707438],
       [-0.70869661,  0.6636838 , -0.95800789, -0.07944077,  0.18730711,
         2.39211668, -1.02735505,  0.02021159,  1.46385011, -0.93352855,
         0.96628239,  1.26750044,  1.16707438],
       [ 0.60467605,  0.6636838 , -0.95800789, -0.07944077, -0.78540365,
        -0.41803981, -1.02735505, -0.7453683 ,  1.46385011,  1.25626701,
        -0.66896473,  1.26750044,  1.16707438],
       [-0.48980117,  0.6636838 , -0.95800789,  1.0717369 , -0.06559768,
        -0.41803981, -1.02735505, -0.91549716, -0.68313005,  1.43874997,
        -0.66896473, -0.72428597,  1.16707438],
       [ 0.93301921,  0.663683

## Training the Kernel SVM model on the Training set

In [14]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state=1)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=1, shrinking=True, tol=0.001,
    verbose=False)

## Predicting a new result

In [15]:
print(classifier.predict(sc.transform([[67, 0, 2, 155, 248, 0, 0, 178, 0, 2.7, 2, 0, 2]])))

[1]


## Predicting the Test set results

In [16]:
y_pred = classifier.predict(X_test)
np.set_printoptions(precision=2)
np.concatenate((y_test.reshape(len(y_test), 1), y_pred.reshape(len(y_pred), 1)), 1)

array([[0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [0, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 0]])

## Making the Confusion Matrix

In [17]:
from sklearn.metrics import precision_score, f1_score, recall_score, accuracy_score, confusion_matrix

confusion_matrix(y_test, y_pred)

array([[20, 10],
       [ 5, 26]])

In [18]:
accuracy_score(y_test, y_pred)

0.7540983606557377

In [19]:
f1_score(y_test, y_pred)

0.7761194029850746

In [20]:
precision_score(y_test, y_pred)

0.7222222222222222

## Visualising the Training set results

## Visualising the Test set results