# Naive Bayes

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv('heart.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [14]:
dataset.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

## Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
print(X_train) 

[[43.  0.  2. ...  1.  0.  2.]
 [66.  0.  2. ...  1.  1.  2.]
 [58.  1.  2. ...  2.  0.  2.]
 ...
 [56.  1.  3. ...  1.  0.  3.]
 [47.  1.  2. ...  2.  0.  2.]
 [58.  1.  1. ...  1.  0.  2.]]


In [5]:
print(y_train)

[1 1 1 0 0 0 0 1 1 1 1 1 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 0 0
 1 0 0 1 0 1 0 0 0 1 1 1 0 0 0 0 1 0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1
 0 1 1 0 0 0 0 1 0 1 1 0 1 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 1 0 1 1 0 1 1 1 1
 1 0 0 1 0 1 0 0 1 0 0 1 1 1 0 0 1 1 0 1 0 1 0 1 1 0 1 1 1 0 1 0 0 0 1 1 1
 1 0 1 0 1 0 1 1 1 0 1 0 1 0 0 0 1 1 0 1 0 1 1 0 0 1 0 1 1 0 1 1 1 1 1 0 0
 1 1 1 0 0 1 1 1 1 1 0 1 1 0 1 1 0 1 1 0 0 1 1 1 0 0 0 1 0 0 1 0 0 1 0 1 1
 0 0 0 0 1 0 1 1 1 0 0 0 0 1 0 0 0 1 1 0]


In [6]:
print(X_test)

[[7.00e+01 1.00e+00 0.00e+00 1.45e+02 1.74e+02 0.00e+00 1.00e+00 1.25e+02
  1.00e+00 2.60e+00 0.00e+00 0.00e+00 3.00e+00]
 [6.40e+01 1.00e+00 3.00e+00 1.70e+02 2.27e+02 0.00e+00 0.00e+00 1.55e+02
  0.00e+00 6.00e-01 1.00e+00 0.00e+00 3.00e+00]
 [5.90e+01 1.00e+00 3.00e+00 1.70e+02 2.88e+02 0.00e+00 0.00e+00 1.59e+02
  0.00e+00 2.00e-01 1.00e+00 0.00e+00 3.00e+00]
 [6.00e+01 1.00e+00 0.00e+00 1.25e+02 2.58e+02 0.00e+00 0.00e+00 1.41e+02
  1.00e+00 2.80e+00 1.00e+00 1.00e+00 3.00e+00]
 [6.20e+01 1.00e+00 2.00e+00 1.30e+02 2.31e+02 0.00e+00 1.00e+00 1.46e+02
  0.00e+00 1.80e+00 1.00e+00 3.00e+00 3.00e+00]
 [4.80e+01 1.00e+00 0.00e+00 1.24e+02 2.74e+02 0.00e+00 0.00e+00 1.66e+02
  0.00e+00 5.00e-01 1.00e+00 0.00e+00 3.00e+00]
 [4.00e+01 1.00e+00 0.00e+00 1.10e+02 1.67e+02 0.00e+00 0.00e+00 1.14e+02
  1.00e+00 2.00e+00 1.00e+00 0.00e+00 3.00e+00]
 [6.30e+01 1.00e+00 0.00e+00 1.30e+02 2.54e+02 0.00e+00 0.00e+00 1.47e+02
  0.00e+00 1.40e+00 1.00e+00 1.00e+00 3.00e+00]
 [5.60e+01 0.00e+00 0.00

In [11]:
print(y_test)

[0 1 0 0 1 0 0 0 0 0 1 1 0 1 1 1 1 1 0 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0
 1 0 0 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 0 1 0 1 1 1]


## Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
print(X_train)

[[-1.32773282 -1.43641607  0.98584243 ... -0.66169316 -0.70710678
  -0.46472917]
 [ 1.24903178 -1.43641607  0.98584243 ... -0.66169316  0.26516504
  -0.46472917]
 [ 0.35276583  0.69617712  0.98584243 ...  0.95577901 -0.70710678
  -0.46472917]
 ...
 [ 0.12869935  0.69617712  1.94013791 ... -0.66169316 -0.70710678
   1.14190596]
 [-0.87959984  0.69617712  0.98584243 ...  0.95577901 -0.70710678
  -0.46472917]
 [ 0.35276583  0.69617712  0.03154696 ... -0.66169316 -0.70710678
  -0.46472917]]


In [12]:
print(X_test)

[[ 1.69716475  0.69617712 -0.92274852  0.77251645 -1.36354075 -0.41803981
   0.90163913 -1.07375268  1.40984195  1.2900049  -2.27916533 -0.70710678
   1.14190596]
 [ 1.02496529  0.69617712  1.94013791  2.23625729 -0.3703119  -0.41803981
  -0.97936664  0.22375805 -0.70929937 -0.38883987 -0.66169316 -0.70710678
   1.14190596]
 [ 0.46479907  0.69617712  1.94013791  2.23625729  0.7728383  -0.41803981
  -0.97936664  0.39675948 -0.70929937 -0.72460883 -0.66169316 -0.70710678
   1.14190596]
 [ 0.57683232  0.69617712 -0.92274852 -0.39847623  0.21063328 -0.41803981
  -0.97936664 -0.38174696  1.40984195  1.45788938 -0.66169316  0.26516504
   1.14190596]
 [ 0.8008988   0.69617712  0.98584243 -0.10572806 -0.29535123 -0.41803981
   0.90163913 -0.16549517 -0.70929937  0.61846699 -0.66169316  2.20970869
   1.14190596]
 [-0.7675666   0.69617712 -0.92274852 -0.45702586  0.51047596 -0.41803981
  -0.97936664  0.69951198 -0.70929937 -0.47278211 -0.66169316 -0.70710678
   1.14190596]
 [-1.66383254  0.69617

## Training the Naive Bayes model on the Training set

In [13]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

## Predicting a new result

In [15]:
print(classifier.predict(sc.transform([[45, 1, 2, 130, 255, 0, 1, 152, 0, 205, 0, 1, 2]])))

[0]


## Predicting the Test set results

In [16]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]]


## Making the Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[21  6]
 [ 3 31]]


0.8524590163934426