In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('heart.csv')
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
df.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, 
                                                    random_state = 1)

In [4]:
X_train

array([[51.,  1.,  3., ...,  2.,  1.,  2.],
       [44.,  1.,  0., ...,  2.,  1.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.],
       ...,
       [29.,  1.,  1., ...,  2.,  0.,  2.],
       [51.,  1.,  0., ...,  2.,  0.,  3.],
       [54.,  1.,  2., ...,  2.,  0.,  3.]])

In [5]:
X_test

array([[62.,  0.,  0., ...,  0.,  3.,  3.],
       [56.,  1.,  1., ...,  2.,  0.,  3.],
       [48.,  1.,  0., ...,  2.,  2.,  3.],
       ...,
       [45.,  0.,  1., ...,  1.,  0.,  2.],
       [58.,  1.,  0., ...,  0.,  3.,  1.],
       [66.,  1.,  1., ...,  1.,  3.,  1.]])

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
X_train

array([[-0.33491521,  0.6355891 ,  1.99223435, ...,  0.9242039 ,
         0.29558577, -0.53505171],
       [-1.09720687,  0.6355891 , -0.94758246, ...,  0.9242039 ,
         0.29558577, -0.53505171],
       [-0.00821878,  0.6355891 , -0.94758246, ..., -0.722277  ,
         0.29558577,  1.13305069],
       ...,
       [-2.73068901,  0.6355891 ,  0.03235647, ...,  0.9242039 ,
        -0.6990838 , -0.53505171],
       [-0.33491521,  0.6355891 , -0.94758246, ...,  0.9242039 ,
        -0.6990838 ,  1.13305069],
       [-0.00821878,  0.6355891 ,  1.01229541, ...,  0.9242039 ,
        -0.6990838 ,  1.13305069]])

In [8]:
X_test

array([[ 0.8629717 , -1.57334352, -0.94758246, ..., -2.36875789,
         2.28492491,  1.13305069],
       [ 0.20957884,  0.6355891 ,  0.03235647, ...,  0.9242039 ,
        -0.6990838 ,  1.13305069],
       [-0.66161163,  0.6355891 , -0.94758246, ...,  0.9242039 ,
         1.29025534,  1.13305069],
       ...,
       [-0.98830806, -1.57334352,  0.03235647, ..., -0.722277  ,
        -0.6990838 , -0.53505171],
       [ 0.42737646,  0.6355891 , -0.94758246, ..., -2.36875789,
         2.28492491, -2.20315412],
       [ 1.29856693,  0.6355891 ,  0.03235647, ..., -0.722277  ,
         2.28492491, -2.20315412]])

In [9]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear', random_state=0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [10]:
y_pred = classifier.predict(X_test)
np.concatenate((y_test.reshape(len(y_test), 1), y_pred.reshape(len(y_pred), 1)), 1)

array([[0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 1],
       [1, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [1,

In [11]:
from sklearn.metrics import precision_score, f1_score, recall_score, accuracy_score, confusion_matrix

confusion_matrix(y_test, y_pred)

array([[29, 12],
       [ 8, 42]])

In [12]:
accuracy_score(y_test, y_pred)

0.7802197802197802

In [13]:
f1_score(y_test, y_pred)

0.8076923076923077

In [14]:
precision_score(y_test, y_pred)

0.7777777777777778