In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('heart.csv')
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
df.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, 
                                                    random_state = 1)

In [ ]:
X_train

array([[51.,  1.,  3., ...,  2.,  1.,  2.],
       [44.,  1.,  0., ...,  2.,  1.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.],
       ...,
       [29.,  1.,  1., ...,  2.,  0.,  2.],
       [51.,  1.,  0., ...,  2.,  0.,  3.],
       [54.,  1.,  2., ...,  2.,  0.,  3.]])

In [ ]:
y_train

array([1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1])

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train[:, :-1] = sc.fit_transform(X_train[:, :-1])
X_test[:, :-1] = sc.transform(X_test[:, :-1])

In [ ]:
X_train

array([[-0.33491521,  0.6355891 ,  1.99223435, ...,  0.9242039 ,
         0.29558577,  2.        ],
       [-1.09720687,  0.6355891 , -0.94758246, ...,  0.9242039 ,
         0.29558577,  2.        ],
       [-0.00821878,  0.6355891 , -0.94758246, ..., -0.722277  ,
         0.29558577,  3.        ],
       ...,
       [-2.73068901,  0.6355891 ,  0.03235647, ...,  0.9242039 ,
        -0.6990838 ,  2.        ],
       [-0.33491521,  0.6355891 , -0.94758246, ...,  0.9242039 ,
        -0.6990838 ,  3.        ],
       [-0.00821878,  0.6355891 ,  1.01229541, ...,  0.9242039 ,
        -0.6990838 ,  3.        ]])

In [ ]:
from sklearn.linear_model import LogisticRegression
reg = LogisticRegression()
reg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
print(reg.predict([[58,1,0,114,318,0,2,140,0,4.4,0,3,1]]))

[0]


In [ ]:
y_pred = reg.predict(X_test)
np.set_printoptions(precision=0.3)
np.concatenate((y_test.reshape(len(y_test), 1), y_pred.reshape(len(y_pred), 1)), 1)

array([[0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 1],
       [1, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [1,

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score
confusion_matrix(y_pred, y_test)

array([[30,  9],
       [11, 41]])

In [29]:
accuracy_score(y_pred, y_test)

0.7802197802197802

In [30]:
f1_score(y_test, y_pred)

0.803921568627451

In [33]:
precision_score(y_test, y_pred)

0.7884615384615384