# Decision Tree Regression

## Importing the libraries

In [26]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt

## Importing the dataset

In [27]:
df = pd.read_excel('AirQualityUCI.xlsx')
df.head()

Date      Time  CO(GT)  ...      T         RH        AH
0 2004-03-10  18:00:00     2.6  ...  13.60  48.875001  0.757754
1 2004-03-10  19:00:00     2.0  ...  13.30  47.700000  0.725487
2 2004-03-10  20:00:00     2.2  ...  11.90  53.975000  0.750239
3 2004-03-10  21:00:00     2.2  ...  11.00  60.000000  0.786713
4 2004-03-10  22:00:00     1.6  ...  11.15  59.575001  0.788794

[5 rows x 15 columns]

In [28]:
df.isnull().sum()

Date             0
Time             0
CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         0
C6H6(GT)         0
PT08.S2(NMHC)    0
NOx(GT)          0
PT08.S3(NOx)     0
NO2(GT)          0
PT08.S4(NO2)     0
PT08.S5(O3)      0
T                0
RH               0
AH               0
dtype: int64

In [29]:
df.drop(labels=['Time'], axis= 1, inplace= True)
df.head()

Date  CO(GT)  PT08.S1(CO)  ...      T         RH        AH
0 2004-03-10     2.6      1360.00  ...  13.60  48.875001  0.757754
1 2004-03-10     2.0      1292.25  ...  13.30  47.700000  0.725487
2 2004-03-10     2.2      1402.00  ...  11.90  53.975000  0.750239
3 2004-03-10     2.2      1375.50  ...  11.00  60.000000  0.786713
4 2004-03-10     1.6      1272.25  ...  11.15  59.575001  0.788794

[5 rows x 14 columns]

In [30]:
df['Date'] = pd.to_datetime(df['Date']).dt.strftime('%Y%m%d%H%M%S%f').apply(lambda x: int(x[:-3]))

## Defining two X variables and joining them to seperate y ('T')

In [31]:
X1 = df.iloc[:, :-3].values
X2 = df.iloc[:, -2:].values
y = df.iloc[:, -3].values

In [32]:
X1

array([[2.0040310e+16, 2.6000000e+00, 1.3600000e+03, ..., 1.1300000e+02,
        1.6920000e+03, 1.2675000e+03],
       [2.0040310e+16, 2.0000000e+00, 1.2922500e+03, ..., 9.2000000e+01,
        1.5587500e+03, 9.7225000e+02],
       [2.0040310e+16, 2.2000000e+00, 1.4020000e+03, ..., 1.1400000e+02,
        1.5545000e+03, 1.0740000e+03],
       ...,
       [2.0050404e+16, 2.4000000e+00, 1.1420000e+03, ..., 1.7470000e+02,
        1.2407500e+03, 1.0920000e+03],
       [2.0050404e+16, 2.1000000e+00, 1.0025000e+03, ..., 1.5570000e+02,
        1.0410000e+03, 7.6975000e+02],
       [2.0050404e+16, 2.2000000e+00, 1.0707500e+03, ..., 1.6770000e+02,
        1.1285000e+03, 8.1600000e+02]])

In [33]:
X2

array([[48.87500095,  0.75775383],
       [47.69999981,  0.72548745],
       [53.97500038,  0.75023907],
       ...,
       [18.34999967,  0.64064877],
       [13.54999995,  0.51386592],
       [13.125     ,  0.50280371]])

In [34]:
X = np.concatenate((X1, X2), axis=1)

In [35]:
X

array([[2.00403100e+16, 2.60000000e+00, 1.36000000e+03, ...,
        1.26750000e+03, 4.88750010e+01, 7.57753825e-01],
       [2.00403100e+16, 2.00000000e+00, 1.29225000e+03, ...,
        9.72250000e+02, 4.76999998e+01, 7.25487449e-01],
       [2.00403100e+16, 2.20000000e+00, 1.40200000e+03, ...,
        1.07400000e+03, 5.39750004e+01, 7.50239067e-01],
       ...,
       [2.00504040e+16, 2.40000000e+00, 1.14200000e+03, ...,
        1.09200000e+03, 1.83499997e+01, 6.40648773e-01],
       [2.00504040e+16, 2.10000000e+00, 1.00250000e+03, ...,
        7.69750000e+02, 1.35500000e+01, 5.13865916e-01],
       [2.00504040e+16, 2.20000000e+00, 1.07075000e+03, ...,
        8.16000000e+02, 1.31250000e+01, 5.02803706e-01]])

In [36]:
y

array([13.5999999 , 13.29999995, 11.9000001 , ..., 26.89999962,
       28.32499981, 28.50000048])

## Splitting Data

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 1)

In [38]:
X_test

array([[ 2.00404140e+16,  1.10000000e+00,  1.04733333e+03, ...,
         1.00300000e+03,  6.14333331e+01,  8.30289051e-01],
       [ 2.00504030e+16,  4.00000000e-01,  8.47750000e+02, ...,
         5.23000000e+02,  5.23750000e+01,  6.07397905e-01],
       [ 2.00403140e+16, -2.00000000e+02,  1.12950000e+03, ...,
         1.05050000e+03,  6.11000013e+01,  8.60316213e-01],
       ...,
       [ 2.00411300e+16,  3.60000000e+00,  1.31200000e+03, ...,
         1.26125000e+03,  7.08750000e+01,  1.10764362e+00],
       [ 2.00409030e+16, -2.00000000e+02,  1.24850000e+03, ...,
         1.28475000e+03,  5.92750006e+01,  1.55231040e+00],
       [ 2.00406260e+16,  1.90000000e+00,  1.09950000e+03, ...,
         9.32000000e+02,  3.38999996e+01,  1.45644837e+00]])

In [39]:
y_test

array([11.46666654,  9.12499976, 12.0999999 , ..., 13.7249999 ,
       22.04999971, 30.50000048])

## Feature Scaling

In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [41]:
X_train

array([[ 1.78232292,  0.47273702,  0.71414089, ...,  0.85434721,
         0.48700944,  0.20059648],
       [-0.45718894,  0.54770336,  1.75701516, ...,  2.76000901,
         0.12831011,  0.18905787],
       [ 1.7786298 ,  0.48436972,  0.63328035, ...,  1.16768146,
         0.25582601,  0.19176903],
       ...,
       [-0.65563293, -2.1472073 , -0.04609933, ..., -0.2417768 ,
         0.42227809,  0.20609558],
       [-0.50889271, -2.1472073 , -0.98393047, ..., -1.19870179,
         0.34683926,  0.20054459],
       [-0.67951515,  0.47144449,  1.34968963, ...,  0.87072356,
         0.16578619,  0.20016873]])

## Training the Decision Tree Regression model on the whole dataset

In [42]:
from sklearn.tree import DecisionTreeRegressor
reg = DecisionTreeRegressor()
reg.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

## Predicting Results

In [43]:
y_pred = reg.predict(X_test)
np.printoptions(precision=2)
np.concatenate((y_test.reshape(len(y_test), 1), y_pred.reshape(len(y_pred), 1)), 1)

array([[11.46666654, 10.95000005],
       [ 9.12499976, 10.05000019],
       [12.0999999 , 11.95000005],
       ...,
       [13.7249999 , 13.95000029],
       [22.04999971, 21.99999952],
       [30.50000048, 30.10000014]])

In [44]:
from sklearn.metrics import mean_squared_error, r2_score
mean_squared_error(y_test, y_pred)

0.43179548503795007

In [45]:
r2_score(y_test, y_pred)

0.9997654483947956

In [46]:
np.sqrt(mean_squared_error(y_test, y_pred))

0.657111470785551